import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Peter lee',
      email: 'Peter.lee@mail.com',
      password: bcrypt.hashSync('44448888'),
      isAdmin: true,
    },
    {
      name: 'Ang John',
      email: 'JA@mail.com',
      password: bcrypt.hashSync('88884444'),
      isAdmin: false,
        },
    {
      name: 'Ang may leee',
      email: 'MLang@mail.com',
      password: bcrypt.hashSync('321321321'),
      isAdmin: false,
        },
    ],
    

    products: [
        {
            //_id: '1',
            name: 'Dental Checkup',
            slug: 'Dental-Checkup',
            category: 'REGULAR DENTAL CHECKUP',
            image: '/images/p1.jpg',
            price: 80,
            countInStock: 8,
            brand: 'Smilz',
            rating: 4.6,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            //_id: '2',
            name: 'Gum Infection Therapy',
            slug: 'Gum-Infection-Therapy',
            category: 'GUM INFECTION THERAPY',
            image: '/images/p2.jpg',
            price: 400,
            countInStock: 5,
            brand: 'Smilz',
            rating: 4.8,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            //_id: '3',
            name: 'Braces for Adults',
            slug: 'Braces-for-Adults',
            category: 'TEETH STRAIGHTENING',
            image: '/images/p3.jpg',
            price: 5700,
            countInStock: 8,
            brand: 'Smilz',
            rating: 4.6,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            //_id: '4',
            name: 'Invisalign',
            slug: 'Invisalign',
            category: 'INVISALIGN',
            image: '/images/p4.jpg',
            price: 6400,
            countInStock: 15,
            brand: 'Smilz',
            rating: 3.0,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            //_id: '5',
            name: 'Root Canal Treatment',
            slug: 'Root-Canal-Treatment',
            category: 'ROOT CANAL TREATMENT',
            image: '/images/p5.jpg',
            price: 3400,
            countInStock: 6,
            brand: 'Smilz',
            rating: 4.5,
            numReviews: 10,
            description: 'No pain during the Canal Treatment',
        },
        {
            //_id: '6',
            name: 'Dental Bridge',
            slug: 'Dental-Bridge',
            category: 'TOOTH REPAIR & REPLACEMENT',
            image: '/images/p6.jpg',
            price: 1000,
            countInStock: 16,
            brand: 'Smilz',
            rating: 4.6,
            numReviews: 10,
            description: 'Good Service',
        },

    ],
};
export default data;