const data ={
    products: [
        {
            name: 'Dental Checkup',
            slug: 'Dental-Checkup',
            category: 'REGULAR DENTAL CHECKUP',
            image: '/images/p1.jpg',
            price: 80,
            countInStock: 8,
            brand: 'Smilz',
            rating: 4.6,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            name: 'Gum Infection Therapy',
            slug: 'Gum-Infection-Therapy',
            category: 'GUM INFECTION THERAPY',
            image: '/images/p2.jpg',
            price: 400,
            countInStock: 5,
            brand: 'Smilz',
            rating: 4.8,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            name: 'Braces for Adults',
            slug: 'Braces-for-Adults',
            category: 'TEETH STRAIGHTENING',
            image: '/images/p3.jpg',
            price: 5700,
            countInStock: 8,
            brand: 'Smilz',
            rating: 4.6,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            name: 'Invisalign',
            slug: 'Invisalign',
            category: 'INVISALIGN',
            image: '/images/p4.jpg',
            price: 6400,
            countInStock: 15,
            brand: 'Smilz',
            rating: 4.7,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            name: 'Root Canal Treatment',
            slug: 'Root-Canal-Treatment',
            category: 'ROOT CANAL TREATMENT',
            image: '/images/p5.jpg',
            price: 3400,
            countInStock: 6,
            brand: 'Smilz',
            rating: 4.5,
            numReviews: 10,
            description: 'Good Service',
        },
        {
            name: 'Dental Bridge',
            slug: 'Dental-Bridge',
            category: 'TOOTH REPAIR & REPLACEMENT',
            image: '/images/p6.jpg',
            price: 1000,
            countInStock: 16,
            brand: 'Smilz',
            rating: 4.6,
            numReviews: 10,
            description: 'Good Service',
        },

    ],
};
export default data;